OpenAPI Definitions/purplship-openapi_2020.6.2.json
OpenAPI Definitions/purplship-openapi_2020.6.2.yaml
purpleserver/core/purpleserver/core/serializers.py
purpleserver/core/purpleserver/core/views/__init__.py
purpleserver/core/purpleserver/core/views/carriers.py
purpleserver/core/purpleserver/core/views/labels.py
purpleserver/core/purpleserver/core/views/utils.py
purpleserver/core/setup.py
purpleserver/proxy/purpleserver/proxy/views/__init__.py
purpleserver/proxy/purpleserver/proxy/views/rates.py
purpleserver/proxy/purpleserver/proxy/views/shipments.py
purpleserver/proxy/purpleserver/proxy/views/tracking.py
purpleserver/proxy/setup.py
purpleserver/purpleserver/urls.py
purpleserver/setup.py
scripts.sh

Cleanup OpenAPI for better client generated

---

.docker/docker-compose.yml
.docker/requirements.txt
README.md
requirements.txt

Release docker image 2020.6.2

---

purpleserver/core/purpleserver/core/datatypes.py
purpleserver/core/purpleserver/core/gateway.py

- Fix Rate response content to match serializer

fix rates request API response

---

.gitignore
purpleserver/core/purpleserver/core/exceptions.py
purpleserver/core/purpleserver/core/gateway.py
purpleserver/proxy/purpleserver/proxy/views/rate.py
purpleserver/purpleserver/settings.py

Cleanup logs and exception handling

---

postgres.yml
purpleserver/purpleserver/settings/__init__.py
purpleserver/purpleserver/settings/base.py
purpleserver/purpleserver/urls.py
purpleserver/tenants/LICENSE
purpleserver/tenants/README.md
purpleserver/tenants/purpleserver/__init__.py
purpleserver/tenants/purpleserver/tenants/admin.py
purpleserver/tenants/purpleserver/tenants/apps.py
purpleserver/tenants/purpleserver/tenants/management/commands/migrate_schemas.py
purpleserver/tenants/purpleserver/tenants/models.py
purpleserver/tenants/purpleserver/tenants/settings.py
purpleserver/tenants/purpleserver/tenants/tests.py
purpleserver/tenants/purpleserver/tenants/urls.py
purpleserver/tenants/purpleserver/tenants/views.py
purpleserver/tenants/setup.py
requirements.test.txt
requirements.txt
scripts.sh

This PR introduces multi-tenant support for purplship-server. The strategy selected based on the methods proposed in https://books.agiliq.com/projects/django-multi-tenant is the `Sharded database with isolated schema` using https://github.com/bernardopires/django-tenant-schemas

[feature] Multi-tenant integration

---

postgres.yml
purpleserver/core/purpleserver/core/fields.py
purpleserver/core/purpleserver/core/gateway.py
purpleserver/core/purpleserver/core/utils.py
purpleserver/pricing/LICENSE
purpleserver/pricing/README.md
purpleserver/pricing/purpleserver/__init__.py
purpleserver/pricing/purpleserver/pricing/__init__.py
purpleserver/pricing/purpleserver/pricing/admin.py
purpleserver/pricing/purpleserver/pricing/apps.py
purpleserver/pricing/purpleserver/pricing/models.py
purpleserver/pricing/purpleserver/pricing/signals.py
purpleserver/pricing/purpleserver/pricing/tests.py
purpleserver/pricing/purpleserver/pricing/views.py
purpleserver/pricing/setup.py
purpleserver/purpleserver/settings/base.py
scripts.sh

[feature] Custom Pricing adjustment panel

---

README.md
docker/Dockerfile
gunicorn-cfg.py
requirements.txt
scripts.sh
src/purpleserver/purpleserver/urls.py
src/purpleserver/setup.py

Release Docker Image 2020.8

---

OpenAPI/purplship-openapi_2020.8.1.json
OpenAPI/purplship-openapi_2020.8.1.yml
docker-compose.yml
scripts.sh
src/apps/core/purpleserver/core/serializers.py
src/apps/core/purpleserver/core/views/references.py
src/apps/core/setup.py
src/apps/proxy/purpleserver/proxy/views/tracking.py
src/apps/proxy/setup.py
src/purpleserver/purpleserver/settings/base.py
src/purpleserver/setup.py

[patch] Bugfixes 2020.8.1

---

README.md
requirements.txt

- Update Readme versions references
- Release docker image 2020.10.1

update versions to 2020.10.1

---

apps/core/purpleserver/core/gateway.py
apps/core/setup.py

Revert shipment cancel fix since the commit was lost.

[patch] handle carrier shipment cancellation not supported

---

requirements.txt

- Fix graphql data requests pagination
- Fix customs update state issues during label creation
- Improve dashboard styling for desktop

[patch] graph pagination and bug fixes

---

apps/client/purpleserver/client/templates/client/index.html
scripts.sh

I'm working on a patch for #154 and had to make a few changes here too.

Improvements for dev experience

---

apps/events/purpleserver/events/tasks/tracking.py
apps/events/setup.py

fix uncaught undefined instance variable on tracking update task

[patch] background tracking task error 

---

src/components/webhook-edit-modal.tsx
src/styles/dashboard.scss
src/views/shipment.tsx
src/views/webhooks.tsx

- Fix webhook list rendering 
- Add tracking number to shipping section in shipment details

[patch] 2022.4.5

---

src/client/context.tsx
src/components/descriptions/options-description.tsx
src/components/form-parts/customs-info-form.tsx
src/components/form-parts/form-modals.tsx
src/components/navbar/navbar.tsx
src/context/label-data-mutation.tsx
src/context/next-session-provider.tsx
src/layouts/dashboard-layout.tsx
src/lib/helper.ts
src/lib/types.ts
src/styles/dashboard.scss
src/views/connections.tsx
src/views/create_label.tsx
src/views/create_shipment.tsx
src/views/order.tsx
src/views/orders.tsx
src/views/shipment.tsx
src/views/shipments.tsx
src/views/trackers.tsx
src/views/webhooks.tsx

- (fix) missing currency displayed 'undefined'
- (fix) draft shipment purchase issue with typo selected_rate_id
- (improve) create shipment form UX with auto data sync
- (fix) stale session issue with GraphQL request client

[patch] Karrio 2022.8.6

---

src/styles/dashboard.scss
src/views/order.tsx
src/views/shipment.tsx

[patch] 2023.1.2

---

src/components/descriptions/shipment-preview.tsx
src/styles/dashboard.scss
src/views/create_shipment.tsx
src/views/shipment.tsx

- (minor) fixes of ETD requirements and shipment cancellation from modal

[patch] 2022.8.22

---

src/components/form-parts/parcel-form.tsx

- (set) your_packaging as default packaging_type

[patch] 2023.8.23

---

src/components/descriptions/shipment-preview.tsx
src/lib/client.tsx
src/lib/data-fetching/index.ts
src/lib/data-fetching/tracker.ts
src/lib/helper.ts
src/pages/api/auth/[...nextauth].ts

- Stabilize multi-tenant support with Vercel

(debug) multi-tenant setup

---

src/context/label-data.ts
src/modules/Shipments/create_label.tsx

- (fix) customs partial pre update state check
- (add) missing default mapper for customs data initialization

[patch] 2023.3.4

---

src/modules/Password/reset/request.tsx

- (fix) error handling on the password reset page

[patch] 2023.4.6 

---

src/lib/data-fetching/tracker.ts

- (improve) tracking page logs

[patch] 2023.5.2
